export const dashboardTypes = {
    SET_DASHBOARD: 'SET_DASHBOARD',
    SET_DEFAULT_DASHBOARD: 'SET_DEFAULT_DASHBOARD',
    // SET_PRODUCTS: 'SET_PRODUCTS',
    // SET_DEFAULT_PRODUCTS: 'SET_DEFAULT_PRODUCTS',
};